name: Doxygen Action
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
        - name: "Doxygen"
          run: |
            sudo apt-get install -y doxygen
            doxygen Doxyfile
